version: '3.4'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.5
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_DEFAULT_APP_MODE=development
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=volkovlabs-rss-datasource,marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-dynamictext-panel
      - ./provisioning:/etc/grafana/provisioning
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana
